image: clojure:latest

include:
  - template: Jobs/Build.gitlab-ci.yml 

variables:
  POSTGRES_DB: sample-test
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: "postgresql://postgres@postgres:5432/sample-test"

services:
  - postgres:12

stages:
  - build
  - test

test:
  stage: test
  script:
    - lein migratus migrate
    - lein test

ancient:
  stage: test
  script:
    - lein ancient
  allow_failure: true

kibit:
  stage: test
  script:
    - lein kibit
