services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: password
  sample:
    restart: never
    image: clojure-sample-ubuntu
    command:
    - "-jar"
    - sample.jar
    environment:
      DATABASE_URL: postgresql://sample:password@postgres:5432/sample
    ports:
      - "3000:3000"
    depends_on:
      - postgres

