FROM clojure AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN lein ring uberjar


FROM openjdk:17-jdk-alpine as runtime
WORKDIR /app
COPY --from=build /usr/src/app/target/sample.jar .
CMD sample.jar